name: 📝 Issue Básica
description: Crie uma issue simples sem um formato específico
title: "[ISSUE]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por abrir uma issue! Por favor, forneça as informações necessárias abaixo.

  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Uma descrição clara e concisa da issue
      placeholder: Descreva o que você gostaria de reportar ou sugerir
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Informações Adicionais
      description: Quaisquer outras informações ou contexto relevante
    validations:
      required: false
