name: 📚 Melhoria de Documentação
description: Sugira melhorias para a documentação
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por ajudar a melhorar nossa documentação! Documentação clara é fundamental para este projeto.

  - type: dropdown
    id: doc_type
    attributes:
      label: Tipo de Documentação
      description: Que tipo de documentação você gostaria de melhorar?
      options:
        - README principal
        - Documentação de uso
        - Guias de solução de problemas
        - Documentação de templates
        - Comentários no código
        - Outro (especifique abaixo)
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Localização
      description: Onde está a documentação que precisa ser melhorada?
      placeholder: "Arquivo docs/troubleshooting.md, seção X..."
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Problema Atual
      description: O que há de errado ou faltando na documentação atual?
      placeholder: "A documentação não explica como..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Sugestão de Melhoria
      description: O que você sugere mudar ou adicionar?
      placeholder: "Deveria explicar que..."
    validations:
      required: true
